printf(
"Suricata Configuration:\n"
"  AF_PACKET support:                       yes\n"
"  PF_RING support:                         no\n"
"  NFQueue support:                         no\n"
"  NFLOG support:                           no\n"
"  IPFW support:                            no\n"
"  Netmap support:                          no\n"
"  DAG enabled:                             no\n"
"  Napatech enabled:                        no\n"
"\n"
"  Unix socket enabled:                     yes\n"
"  Detection enabled:                       yes\n"
"\n"
"  Libmagic support:                        yes\n"
"  libnss support:                          yes\n"
"  libnspr support:                         yes\n"
"  libjansson support:                      yes\n"
"  hiredis support:                         no\n"
"  Prelude support:                         no\n"
"  PCRE jit:                                yes\n"
"  LUA support:                             no\n"
"  libluajit:                               no\n"
"  libgeoip:                                no\n"
"  Non-bundled htp:                         no\n"
"  Old barnyard2 support:                   no\n"
"  CUDA enabled:                            no\n"
"  Hyperscan support:                       no\n"
"  Libnet support:                          yes\n"
"\n"
"  Suricatasc install:                      yes\n"
"\n"
"  Profiling enabled:                       no\n"
"  Profiling locks enabled:                 no\n"
"\n"
"Development settings:\n"
"  Coccinelle / spatch:                     no\n"
"  Unit tests enabled:                      no\n"
"  Debug output enabled:                    no\n"
"  Debug validation enabled:                no\n"
"\n"
"Generic build parameters:\n"
"  Installation prefix:                     /usr/local\n"
"  Configuration directory:                 /usr/local/etc/suricata/\n"
"  Log directory:                           /usr/local/var/log/suricata/\n"
"\n"
"  --prefix                                 /usr/local\n"
"  --sysconfdir                             /usr/local/etc\n"
"  --localstatedir                          /usr/local/var\n"
"\n"
"  Host:                                    x86_64-pc-linux-gnu\n"
"  Compiler:                                gcc (exec name) / gcc (real)\n"
"  GCC Protect enabled:                     no\n"
"  GCC march native enabled:                yes\n"
"  GCC Profile enabled:                     no\n"
"  Position Independent Executable enabled: no\n"
"  CFLAGS                                   -g -O2 -march=native\n"
"  PCAP_CFLAGS                               -I/usr/local/include\n"
"  SECCFLAGS                                \n"
);
